namespace AsyncWebAppDemo.Models
{
    public class TableDemoModel
    {
        public List<IndustrySector> IndustrySectorList
        {
            get
            {
                return new List<IndustrySector>
                {
                    new IndustrySector { Id = 1, Title = "Cybersecurity", Description = "Security is a major IT industry, as most other IT industries need security to support their work. Cybersecurity focuses on protecting IT networks, computer systems and programs from digital attacks, such as viruses and hackers. It keeps pace with comprehensive IT advancement and develops adaptations to counter growing sophistication in digital attacks by using digital technologies and other tools such as firewalls and counter-hacking. It also prevents data leaks and protects vulnerable information with cryptography and other practices." },
                    new IndustrySector { Id = 2, Title = "Software", Description = "The software industry is the sector of IT that focuses on developing software products and software solutions. The two primary forms of software are local software, which the user downloads, hosts and maintains, and software as a service (SaaS). A vendor hosts, maintains and supports SaaS, which usually exists on the cloud for users to access through a browser or mobile app." },
                    new IndustrySector { Id = 3, Title = "Hardware and equipment", Description = "Employees in the hardware and equipment industry design and manufacture IT hardware. This industry places more focus on technology for businesses or other IT industries rather than consumer-facing hardware, which includes computers, tablets and smartphones. Hardware and equipment can include computers, servers, storage devices and networking equipment."},
                    new IndustrySector { Id = 4, Title = "Artificial intelligence", Description = "Employees who work in artificial intelligence focus on designing and producing smart machines, or any machine that can learn, reason and make decisions. AI is also an increasingly large part of everyday life, as it includes mobile phone smart assistants, email spam filters and social media or streaming site algorithms."},
                    new IndustrySector { Id = 5, Title = "Education and training", Description = "Many schools use technology as part of their educational model, both for in-person learning and remote learning. They often use software, hardware and other education-specific IT services that the IT education and training industry provides. This industry often uses positions such as IT trainers or IT educators who teach technology to students and teachers who want to work in the industry."},
                    new IndustrySector { Id = 6, Title = "Data services", Description = "The data services industry relates to the storing, maintaining and use of data, often extremely large amounts of data. This can include data that cloud computing or dedicated servers store. Data services can help collect, transfer and analyze data or use it to create a central database. Organizations often hire data scientists and data analysts to collect, curate and send data and perform data analysis."},
                    new IndustrySector { Id = 7, Title = "Business services", Description = "People working in IT business services develop, implement and maintain technological services for businesses. This can include a business' IT network, telecommunications and IT consulting services. IT business services can also include business-specific software, like a recruiting service or an application management system."},
                    new IndustrySector { Id = 8, Title = "Public infrastructure", Description = "Many cities use unique connected devices to gather, analyze and use data to improve many aspects of their city. These can include increasing the efficiency of a city's utilities to reduce waste and conserve resources, managing transportation systems and monitoring for potential hazards, like floods and landslides. People who work in the industry design the systems that allow cities to accomplish these tasks and provide ongoing support for the systems."},
                    new IndustrySector { Id = 9, Title = "Telecommunications", Description = "The telecommunications industry focuses on implementing and maintaining communication networks. There are many services that fall under telecommunications, such as internet providers, cellular networks, broadcast networks and emergency communications systems. Someone working in telecommunications may also be responsible for the internal communication network of an organization, including office phones, the organization's email network and video conferencing network."},
                    new IndustrySector { Id = 10, Title = "IT consulting", Description = "IT consultants work on contracts for clients, usually companies, to provide IT services. Sometimes, the services focus on a single aspect, like designing and implementing a new system, and sometimes they cover a client's entire network. An IT consultant can audit a company's IT network for strengths and weaknesses, make suggestions on how to improve it, design or select software and hardware and help implement the solutions."},
                    new IndustrySector { Id = 11, Title = "Finance", Description = "IT financial services relate to the technology used in financial systems, like banks. Common forms of financial services include the technology used for bank accounts, investments, financial transactions and payment systems. IT financial services can also include maintaining the infrastructure of larger financial markets."},
                    new IndustrySector { Id = 12, Title = "Simulation", Description = "IT employees in the simulation industry design, implement and maintain these simulated systems to mimic the real world as accurately as possible. Simulations can have a visual component but can also be technological models that provide data. With augmented reality (AR), users can manipulate their presence in the real world. Uses of simulation can include training employees in tasks like flying a plane, testing scientific theories and evaluating economic or financial models. Virtual reality (VR) uses technology to immerse users in a fictional world."},
                    new IndustrySector { Id = 13, Title = "Robotics", Description = "The robotics industry creates machines that can take independent actions. Engineers can program them for a relatively simple repetitive task, like an automated car wash, or they can be more complex and combined with AI. Types of robots include industrial robots used in factories and consumer robots used for entertainment or to complete daily tasks, like robot vacuums."},
                    new IndustrySector { Id = 14, Title = "Creative services", Description = "People who work in the IT industry also offer creative services, which can cover a wide range of creative areas, such as graphic design, advertising and landscaping. They use technology and creativity to create a product or perform a service for a client, which includes individuals and companies. Some other examples of creative services are creating user experiences on apps or websites, designing brands and facilitating aspects of technological design in urban planning."},
                    new IndustrySector { Id = 15, Title = "Research and development", Description = "The research and development industry focuses on creating and implementing technology that supports research, which can include scientific and medical research. They may use technology, like software and data services, to support product development. This can include research and development within other IT industries, such as supporting the advancement of AI. These employees also tend to be where emerging technology develops since the goal is to create advanced technologies or business processes from the research."},
                    new IndustrySector { Id = 16, Title = "Energy", Description = "The energy industry involves managing energy-related infrastructure. These can be small-scale forms of infrastructure, but they can also include city-wide power grids. The IT energy industry also advances technological solutions to energy challenges, like creating more efficient and eco-friendly forms of energy."},
                    new IndustrySector { Id = 17, Title = "Medical", Description = "People in the IT medical industry work with medical technology and systems that medical providers use. These can include more basic forms of technology, like secure data services, and more advanced medical technology like robotic surgery. Other examples of medical technology that you may work with within this industry include telehealth systems, simulations for training and 3D printing of prosthetics."},
                    new IndustrySector { Id = 18, Title = "Sales and marketing", Description = "Technologies of all types, whether they're integrated, stand-alone, business, industrial or consumer, need marketing and sales to be understandable and achieve product success. Sometimes, IT employees have the best capacity to explain and sell this type of product and service. This industry can also make specific technology to support people who work in sales and marketing, such as customer relationship management systems, point of sale systems and financial software. Another large part of this industry is e-commerce, or the selling of products online."},
                    new IndustrySector { Id = 19, Title = "Gaming", Description = "The video game industry encompasses many forms of technology. This can include software for making games, the servers used to host online games and the creation of simulated environments for virtual reality games. Other examples of gaming technology include the design and manufacturing of new game consoles and controllers."},
                    new IndustrySector { Id = 20, Title = "Consumer products and services", Description = "IT employees who work with consumer products may focus on designing new electronics, like cell phones, tablets, fitness trackers and wireless earbuds. This industry may also add internet connectivity to common products, such as a toothbrush that connects to a mobile app or kitchen appliances that you can turn on and off with your phone. IT employees in consumer goods may also be involved in the marketing of these products."}

                };
            }
        }
    }
}
